import java.util.*;

/**
	This program asks users to guess a randomly generated number
	then the program will tell the user if their guess was correct
	or not.
*/


//This class is the driver
public class RandomNumberGuesser {
	
	public static void main(String[] args)
	{
		Scanner keyboard = new Scanner(System.in); //Creates scanner object
		RNG rng = new RNG(); //Creates rng object to use RNG class
		
		//Declares variables
		int randNum; //Will hold number generated by the RNG class
		int nextGuess; //Will hold the next guess from the user
		int highGuess = 100; //Holds a guess that was too high that the user must enter a guess below
		int lowGuess = 0; //Holds a guess that was too low that the user must enter a guess above
		int repeatGame = 0; //Will hold 1 or 2 to repeat game or exit
		
		
		randNum = rng.rand(); //Store the randomly generated number in int variable randNum
		
		do
		{
			do
			{
				System.out.println("Enter a number between " + lowGuess + " and " + highGuess); //Prompts user to enter a guess
				nextGuess = keyboard.nextInt(); //Assign user guess to variable nextGuess
				
				if(nextGuess < 0 || nextGuess > 100)
				{
					System.out.println("\nPlease enter a number within the parameters asked.\n"); //error message for incorrect input
				}
			} while(nextGuess <= 0 || nextGuess >= 100); //Repeat if the guess is not between 0 and 100
			
					
			while (nextGuess != randNum) //While the guess is incorrect repeat
			{
				if(rng.getCount()/2 != 0)
				{
					System.out.println("Your guess count is " + rng.getCount()/2);			
				}
				
				while(!(rng.inputValidation(nextGuess, lowGuess, highGuess))) //While inputValidation returns false
				{
					nextGuess = keyboard.nextInt();
				}
				
				if(nextGuess > randNum) //If nextGuess is too high
				{
					System.out.println("Your guess is too high.");
					highGuess = nextGuess; //Assign user guess to highGuess variable
				}
				else if (nextGuess < randNum) //If nextGuess is too low
				{
					System.out.println("Your guess is too low.");
					lowGuess = nextGuess;
				}
				
				if(nextGuess == randNum) //If the guess is correct!
				{
					System.out.println("Congratulations you guessed correctly!");	
					System.out.println("Would you like to play again?");
					System.out.print("Please enter 1 for yes and 2 for no: ");
					repeatGame = keyboard.nextInt();				
				}
			}
			highGuess = 100;
			lowGuess = 0;
			rng.resetCount();
			randNum = rng.rand();
		} while(repeatGame == 1);
		System.exit(0);
	}

}
